[versions]
project-utilities = "3.1.0"
android = "8.11.1"

[libraries]
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "android" }
gson = "com.google.code.gson:gson:2.13.1"
xmlUnit = "org.xmlunit:xmlunit-core:2.10.3"

#Testing
junit-bom = "org.junit:junit-bom:5.13.4"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
assertj = "org.assertj:assertj-core:3.27.6"
mockk = "io.mockk:mockk:1.14.6"

[bundles]
junit = ["junit-jupiter", "junit-launcher", "junit-engine"]

[plugins]
java-library = { id = "com.likethesalad.tools.java-library", version.ref = "project-utilities" }
artifactPublisher = { id = "com.likethesalad.artifact-publisher", version = "3.4.0" }
androidTestTools = { id = "com.likethesalad.tools.android-compilation-testing", version.ref = "project-utilities" }
android-application = { id = "com.android.application", version.ref = "android" }
wire = { id = "com.squareup.wire", version = "5.4.0" }
