[versions]
project-utilities = "3.1.0"
dagger = "2.57.1"
android = "8.12.1"

[libraries]
resourceLocator = "com.likethesalad.tools.resources:string-android-resource-locator:2.4.0"
androidCompatApi = { module = "com.likethesalad.tools:agp-compatibility-api", version.ref = "project-utilities" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
metadataConsumer = "com.likethesalad.tools:plugin-metadata-consumer:1.0.0"
unitTesting = { module = "com.likethesalad.tools:unit-testing", version.ref = "project-utilities" }
byteBuddy = "net.bytebuddy:byte-buddy:1.17.7"
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "android" }
classGraph = "io.github.classgraph:classgraph:4.8.180"
gson = "com.google.code.gson:gson:2.13.1"
zip4j = "net.lingala.zip4j:zip4j:2.11.5"
robolectric = "org.robolectric:robolectric:4.15.1"
xmlUnit = "org.xmlunit:xmlunit-core:2.10.3"

[plugins]
java-library = { id = "com.likethesalad.tools.java-library", version.ref = "project-utilities" }
artifactPublisher = { id = "com.likethesalad.artifact-publisher", version = "3.3.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.7" }
androidTestTools = { id = "com.likethesalad.tools.android-compilation-testing", version.ref = "project-utilities" }
android-application = { id = "com.android.application", version.ref = "android" }
