[versions]
project-utilities = "3.1.0"
android = "8.13.1"

[libraries]
robolectric = "org.robolectric:robolectric:4.16"
unitTesting = { module = "com.likethesalad.tools:unit-testing", version.ref = "project-utilities" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version = "2.2.20" }